export enum EErrorCode {
    MISSING_QUERY_DATA = "E01",
    MISSING_BODY_DATA = "E02",
    INCORRECT_PASSWORD = "E03",
    EMAIL_ALREADY_EXISTS = "E04",
    EMAIL_INCORRECT = "E05",
    DATA_NOT_FOUND = "E06",
    DATA_ALREADY_EXISTS = "E07",
    MISSING_HEADER_DATA = "E08",
    AUTHORIZATION_ERROR = "E09",
}